module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./comps/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Majalla", "sans-serif"],
      },
    },
    colors: {
      "pri-color": "#9AD0EC",
      "sec-color": "#1572A1",
      "white": "#fff",
      "black": "#000",
      "ter-color": "#EFDAD7",
      "green-1": "#35D1BE",
       "trans": "#00000000",
       "backor": "#fbf8ef",



      "primary-light": "#006c4d",
      "on-primary-light": "#ffffff",
      "primary-container-light": "#86f8c9",
      "on-primary-container-light": "#002115",
      "secondary-light": "#006d3e",
      "on-secondary-light": "#ffffff",
      "secondary-container-light": "#87f9b5",
      "on-secondary-container-light": "#00210f",
      "tertiary-light": "#7D5260",
      "on-tertiary-light": "#FFFFFF",
      "tertiary-container-light": "#FFD8E4",
      "on-tertiary-container-light": "#31111D",
      "error-light": "#B3261E",
      "on-error-light": "#FFFFFF",
      "error-container-light": "#F9DEDC",
      "on-error-container-light": "#410E0B",
      "outline-light": "#79747E",
      "background-light": "#FFFBFE",
      "on-background-light": "#1C1B1F",
      "surface-light": "#FFFBFE",
      "on-surface-light": "#1C1B1F",
      "surface-variant-light": "#E7E0EC",
      "on-surface-variant-light": "#49454F",
      "inverse-surface-light": "#313033",
      "inverse-on-surface-light": "#F4EFF4",
      "primary-dark": "#69dbae",
      "on-primary-dark": "#003826",
      "primary-container-dark": "#005138",
      "on-primary-container-dark": "#86f8c9",
      "secondary-dark": "#6bdc9b",
      "on-secondary-dark": "#00391e",
      "secondary-container-dark": "#00522d",
      "on-secondary-container-dark": "#87f9b5",
      "tertiary-dark": "#EFB8C8",
      "on-tertiary-dark": "#492532",
      "tertiary-container-dark": "#633B48",
      "on-tertiary-container-dark": "#FFD8E4",
      "error-dark": "#F2B8B5",
      "on-error-dark": "#601410",
      "error-container-dark": "#8C1D18",
      "on-error-container-dark": "#F9DEDC",
      "outline-dark": "#938F99",
      "background-dark": "#1C1B1F",
      "on-background-dark": "#E6E1E5",
      "surface-dark": "#1C1B1F",
      "on-surface-dark": "#E6E1E5",
      "surface-variant-dark": "#49454F",
      "on-surface-variant-dark": "#CAC4D0",
      "inverse-surface-dark": "#E6E1E5",
      "inverse-on-surface-dark": "#1C1B1F",

    }
  },
  plugins: [
    require('tailwindcss-rtl'),
  ],
}
